### ISSUE TITLE
Tracking: Address Oak Security Audit Report Findings

### ISSUE THREAD

**Issue by NotJeremyLiu** [skip-mev/skip-api-contracts#2]
Issues to close / resolve:
- [x] #3 
- [x] #4 
- [x] #5 
- [x] #6 
- [x] #7 
- [x] #8 
- [x] #9 
- [x] #10 
- [x] #11 
- [x] #12

**Comment by NotJeremyLiu** [comment]
@cfkelly18 I believe now all the audit resolutions are complete, with the only thing still left is to check out the PR linked in the google doc to see if that's a better approach from a security perspective, upwards and onwards

**Comment by cfkelly18** [comment]
thanks @NotJeremyLiu! Thats correct! We are reviewing that pr and will get back to you as soon as possible. Just want to make sure all of our auditors have a chance to spend some time on it!
