### ISSUE TITLE
feature request: Swap output amount event

### ISSUE THREAD

**Issue by PoolPirate** [skip-mev/skip-api-contracts#95]
## Background
I'm integrating the Skip API contracts for some automated cross-chain trading. One of the upsides I was looking for is not having to integrate swap routers on all the DEXes in Cosmos (which works well).
My code requires to know what the output amount of each swap was, however the contracts do not emit this information in any event.

This leaves me having to manually parse the events emitted by each swap venue which defeates one of the purposes of using Skip contracts in the first place :/

## Suggestion
Emit swap information via contract events. For my use case it would be sufficient to have the final output amount accessible through a common event across swap venues.
Would suggest adding it to the `execute_post_swap_action` event. Example implementation https://github.com/skip-mev/skip-api-contracts/commit/c11130606efe526f76feed41c0a50a6b8b0e261b
(Wouldn't merge that example btw, this wouldn't properly work with IBC fees, would it?)

**Comment by NotJeremyLiu** [comment]
Hey @PoolPirate ! This sounds like a great idea, we're have in the todo list an event emission refactor, will make sure this is included and/or that it gets into the next deploy

**Comment by PoolPirate** [comment]
Sounds great ty, will hold off on decoding the venue events then
