### ISSUE TITLE
python3.10 deploy.py osmosis mainnet and failed

### ISSUE THREAD

**Issue by EasonTheJolter** [skip-mev/skip-api-contracts#97]
transaction failed on chain: https://www.mintscan.io/osmosis/tx/90780C29396380279A0FCC01C025C891EE56CF9CEB18774530A7072ADDFBD24B
seems my account has no permission to deploy a contract.

**Comment by PoolPirate** [comment]
Osmosis contracts are not permissionless. It requires a goverance proposal to either upload a contract or whitelist an address for deployments.

**Comment by NotJeremyLiu** [comment]
@EasonTheJolter What's your use case for deploying the skip api contracts on chain? Can you not use the ones already deployed by Skip?

**Comment by EasonTheJolter** [comment]
> @EasonTheJolter What's your use case for deploying the skip api contracts on chain? Can you not use the ones already deployed by Skip?

is the first time I came into contact with wasm and tried the deployment process. Now I know it. 🤝

**Comment by EasonTheJolter** [comment]
Thanks for your answers
